openapi: 3.0.1
info:
  title: Virtual platform data record APIs
  description: EJPRD virtual platform data record APIs
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: v1.0
servers:
- url: /
paths:
  /individuals:
    post:
      summary: Request to count individuals in a data source (i.e. patients)
      operationId: individuals_request
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IndividualRequest'
        required: false
      responses:
        200:
          $ref: '#/components/schemas/IndividualResponse'
        400:
          description: Input data malformed
          content: {}
        403:
          description: The data source does not allow counting entities
          content: {}
      security:
      - bearerAuth: []
      x-codegen-request-body-name: body
components:
  schemas:
    IndividualRequest:
      required:
      - query
      type: object
      properties:
        query:
          $ref: '#/components/schemas/RequestQuery'
      description: Request to return individuals count for given CDEs input parameters
    RequestQuery:
      type: object
      properties:
        disease:
          $ref: '#/components/schemas/DiseaseField'
        gender:
          $ref: '#/components/schemas/GenderField'
      description: CDEs as input of the query
    DiseaseField:
      type: object
      properties:
        id:
          type: string
          description: |
            Orphanet disease concept url.
          example: ""
      description: |
        Field to filter by disease.
    GenderField:
      type: object
      properties:
        id:
          type: string
          description: |
            CDE gender concept url.
          example: ""
          enum:
          - http://purl.obolibrary.org/obo/NCIT_C16576
          - http://purl.obolibrary.org/obo/NCIT_C20197
          - http://purl.obolibrary.org/obo/NCIT_C124294
          - http://purl.obolibrary.org/obo/NCIT_C17998
        operator:
          type: string
          description: |
            Logical operator's (e.g '=', '!=')
          example: ""
          enum:
          - =
          - '!='
      description: |
        Field to filter by gender.
    IndividualResponse:
      required:
      - response
      type: object
      properties:
        response:
          $ref: '#/components/schemas/IndividualResponseContent'
      description: |
        Response of a query over individuals counts.
    IndividualResponseContent:
      required:
      - exists
      - numTotalResults
      type: object
      properties:
        exists:
          type: boolean
          description: |
            Indicator of whether any individual was observed in the
            data source for the given query with CDEs parameter. This should be non-null, unless there was an error, in which case `error` has to be non-null.
        numTotalResults:
          type: integer
      description: |
        Response of the query indicating if the query yield any results. If the query is successful then the count will be returned as a response.
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
