swagger: "2.0"
info:
  description: "Virtual platform data source API"
  version: "v0.1"
  title: "Virtual platform data source API"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
basePath: "/"
schemes:
- "https"
paths:
  /individuals:
    post:
      summary: "Create a new request to count individuals available at the data source (i.e. patients)"
      description: ""
      operationId: "individuals_request"
      parameters:
      - in: "body"
        name: "body"
        required: false
        schema:
          $ref: "#/definitions/IndividualRequest"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "400":
          description: Input data malformed
        "200":
          $ref: "#/definitions/IndividualResponse"
        "403":
          description: The data source does not allow counting entities
definitions:
  IndividualRequest:
    type: "object"
    description: "Request to return count of individuals with CDEs input parameters"
    required:
      - query
    properties:
        query:
          $ref: '#/definitions/RequestQuery'
  RequestQuery:
      description: "CDEs as input for query"
      type: object
      properties:
        disease:
          $ref: '#/definitions/DiseaseField'
        gender:
          $ref: '#/definitions/GenderField'
  DiseaseField:
      description: |
        Field to filter by disease.
      type: object
      properties:
        id:
          description: |
            Orphanet disease concept url.
          type: string
          example: ["http://www.orpha.net/ORDO/Orphanet_558"]
  GenderField:
      description: |
        Field to filter by gender.
      type: object
      properties:
        id:
          description: |
            CDE gender concept url.
          type: string
          enum: ["http://purl.obolibrary.org/obo/NCIT_C16576",
          "http://purl.obolibrary.org/obo/NCIT_C20197",
          "http://purl.obolibrary.org/obo/NCIT_C124294",
          "http://purl.obolibrary.org/obo/NCIT_C17998"]
          example: ["http://purl.obolibrary.org/obo/NCIT_C16576"]
        operator:
          description: |
            Logical operator's (e.g '=', '!=')
          type: string
          enum: ["=", "!="]
          example: ["="]
  IndividualResponse:
      description: |
        Response of a query over individuals.
      type: object
      required:
        - response
      properties:
        response:
          $ref: '#/definitions/IndividualResponseContent'
  IndividualResponseContent:
      description: |
        Description pending
      type: object
      required:
        - exists
        - numTotalResults
      properties:
        exists:
          description: |
            Indicator of whether any individual was observed in any of the
            datasets queried. This should be non-null, unless there was an
            error, in which case `error` has to be non-null.
          type: boolean
        numTotalResults:
          type: integer
          minimum: 0
